# Generated by Django 5.1.6 on 2026-04-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="LogoutFeedback",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveSmallIntegerField()),
                ("feedback", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="logout_feedbacks",
                        to="accounts.user",
                    ),
                ),
            ],
            options={
                "db_table": "logout_feedback",
                "ordering": ["-created_at"],
            },
        ),
    ]
