# Generated by Django 5.1.6 on 2026-03-06 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SymptomImageAnalysis",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.FileField(upload_to="symptom_images/")),
                ("category", models.CharField(choices=[("skin_rash", "Skin Rash"), ("eye_redness", "Eye Redness")], max_length=30)),
                ("assessment", models.CharField(max_length=200)),
                ("confidence", models.FloatField(default=0.0)),
                ("guidance", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="image_analyses", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "symptom_image_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatRating",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.PositiveSmallIntegerField()),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="ratings", to="chatbot.chathistory"),
                ),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="chat_ratings", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "db_table": "chat_rating",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="chatrating",
            constraint=models.UniqueConstraint(fields=("user", "chat"), name="unique_chat_rating_per_user"),
        ),
    ]
