# Generated by Django 5.1.6 on 2026-03-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_symptom_image_analysis_chat_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="chathistory",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="chat_images/"),
        ),
    ]
