# Generated by Django 5.1.6 on 2026-03-21 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chathistory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.JSONField(default=list)),
                ('answers', models.JSONField(default=list)),
                ('current_index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='followup', to='chatbot.chathistory')),
            ],
            options={
                'db_table': 'chat_followups',
                'ordering': ['-created_at'],
            },
        ),
    ]
