# Generated by Django 5.1.6 on 2026-03-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_chatfollowup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatFollowUp',
        ),
    ]
